HTTP/1.0 503 Service Unavailable
Cache-Control: no-cache
Connection: close
Content-Type: text/html

<html>
    <head>
        <title>The Leapfrog printer software failed to start.</title>
        <style>
            body {
                margin: 0;
                font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
                font-size: 14px;
                line-height: 20px;
                color: #333333;
                background-color: #ffffff;
            }

            @media (max-width: 767px) {
                .wrapper {
                    padding: 20px;
                }
            }

            @media (min-width: 768px) {
                .wrapper {
                    position: absolute;
                    width: 750px;
                    height: 450px;
                    top: 50%;
                    left: 50%;
                    margin: -225px 0 0 -375px;
                }
            }

            h1 {
                line-height: 1.3;
            }
        </style>
    </head>
    <body>
        <div class="wrapper">
            <h1>The Leapfrog printer software failed to start.</h1>
            <h3>
                Please restart your printer.
            </h3>
            <p>
                If the issue persists, please perform a factory reset. You may start a factory reset by holding the power button down for 15 seconds.
            </p>
        </div>
    </body>
</html>