accessControl:
  autologinAs: lpfrg
  autologinLocal: true
  localNetworks:
  - 127.0.0.1/8
appearance:
  name: Bolt
feature:
  modelSizeDetection: false
plugins:
  _disabled:
  - cura
  - pluginmanager
  - announcements
  - softwareupdate
  - corewizard
  discovery:
    publicPort: 80
  flasharduino:
    avrdude_path: /usr/bin/avrdude
  lui:
    changelog_version: 1.0.0
    model: Bolt
  softwareupdate:
    _config_version: 4
    check_providers:
      networkmanager: networkmanager
printerProfiles:
  default: bolt
serial:
  autoconnect: true
  baudrate: 250000
  log: false
  port: /dev/ttyUSB0
  timeout:
    communication: 150
    connection: 5
server:
  commands:
    serverRestartCommand: sudo service octoprint restart
    systemRestartCommand: sudo shutdown -r now
    systemShutdownCommand: sudo shutdown -h now
  firstRun: false
system:
  actions:
  - action: update_lui
    command: cd /home/pi/OctoPrint-LUI && git pull && /home/pi/OctoPrint/venv/bin/python
      setup.py install
    confirm: false
    name: Update LUI
  - action: update_networkmanager
    command: cd /home/pi/OctoPrint-NetworkManager && git pull && /home/pi/OctoPrint/venv/bin/python
      setup.py install
    confirm: false
    name: Update NetworkManager
  - action: update_octoprint
    command: cd /home/pi/OctoPrint && git pull && /home/pi/OctoPrint/venv/bin/python
      setup.py install
    confirm: false
    name: Update OctoPrint
  - action: update_flasharduino
    command: cd /home/pi/OctoPrint-flashArduino && git pull && /home/pi/OctoPrint/venv/bin/python
      setup.py install
    confirm: false
    name: Update Flash Firmware Module
  - action: update_gcoderender
    command: cd /home/pi/OctoPrint-gcodeRender && git pull && /home/pi/OctoPrint/venv/bin/python
      setup.py install
    confirm: false
    name: Update Gcode Render Module
temperature:
  profiles:
  - bed: 70
    extruder: 230
    name: ABS
  - bed: 40
    extruder: 200
    name: PLA
  - bed: 50
    extruder: 240
    name: Flex
  - bed: 60
    extruder: 240
    name: PET
  - bed: 45
    extruder: 195
    name: PVA
  - bed: 45
    extruder: 205
    name: pva1
  - bed: 60
    extruder: 200
    name: petg
  - bed: 70
    extruder: 230
    name: hybrid
  - bed: 60
    extruder: 210
    name: petg2
  - bed: 70
    extruder: 230
    name: Nylon
  - bed: 80
    extruder: 270
    name: HT
  - bed: 0
    extruder: 200
    name: Pro1
  - bed: 60
    extruder: 220
    name: Proone
webcam:
  ffmpeg: /usr/bin/avconv
  snapshot: http://127.0.0.1:8080/?action=snapshot
  stream: http://127.0.0.1:8080/?action=stream
  timelapse:
    fps: 25
    options:
      interval: 10
    postRoll: 0
    type: timed
