#!/usr/bin/env bash
set -x

echo "--- Making root read-only"
echo "--- Preparing overlay"
cp -f /home/pi/scripts/overlay /usr/share/initramfs-tools/scripts/overlay

pushd /usr/share/initramfs-tools
	grep -q "overlay" hook-functions || sed -i "528s@usbhid@usbhid overlay@g" hook-functions
	pushd scripts
		cp -rpf local-premount overlay-premount
		cp -rpf local-bottom overlay-bottom
	popd
popd

kernelv=$(uname -r)

echo "--- Kernel version: $kernelv"
echo "--- Updating initramfs"
update-initramfs -c -k $kernelv

echo "--- Configuring /boot"
pushd /boot
	mv -f "initrd.img-$kernelv" "initrd7.img"

	grep -q "overlay" cmdline.txt || sed -i '1s@^@boot=overlay @' cmdline.txt
	grep -q "kernel=kernel7.img" config.txt || echo "kernel=kernel7.img" >> config.txt
	grep -q "initramfs initrd7.img" config.txt || echo "initramfs initrd7.img" >> config.txt
popd

echo "--- Done. Be sure to reboot!"