#! /bin/sh
### BEGIN INIT INFO
# Provides: dorotatetouch
# Required-Start: $all
# Required-Stop:
# Should-Start:
# Default-Start: 5
# Default-Stop:
# Short-Description: Rotates touch input
# Description: Rotates touch input
### END INIT INFO

case "$1" in
  start)
   export DISPLAY=:0
   id=$(xinput -list | awk -v search="BYZ|WaveShare" '$0 ~ search {match($0, /id=[0-9]+/); if(RSTART) print substr($0, RSTART+3, RLENGTH-3) }');
   rot_mat="0 1 0 -1 0 1" #0 -1 1 1 0 0 for 90deg
   xinput set-float-prop $id "Coordinate Transformation Matrix" $rot_mat 0 0 1
  ;;
  *)
  echo "Usage: dorotatetouch [start]"
    exit 3
  ;;
esac


