#!/usr/bin/env bash
set -x
echo "" > /dev/null

source /common.sh
install_chroot_fail_on_error_trap

mkdir /home/pi/.config -p
chown -hR pi:pi /home/pi/.config

apt-get update

apt-get install --yes raspberrypi-ui-mods lightdm pcmanfm xinit lxterminal xinput

echo "--- Setting up to boot to desktop"
systemctl set-default graphical.target

echo "--- Removing uninstalled applications from desktop"
# we make sure that non of the non-installed packages show up in either
# the default lxde panel or menu
basefolder="/usr/share/raspi-ui-overrides/applications/"
lxde_panel_file="/etc/xdg/lxpanel/profile/LXDE-pi/panels/panel"
files="libreoffice-draw libreoffice-math libreoffice-startcenter bluej greenfoot wolfram-mathematica wolfram-language"

for entry in $files
do
        desktop_file="$basefolder$entry.desktop"

        # hide .desktop file from menu
        grep "Hidden: true" $desktop_file || echo "Hidden: true" >> $desktop_file

        # remove any links to it from panel
        # No need for now, removing complete panelfile anyway
        #perl -i -p0e 's!\s*Button {\n\s*id='"$desktop_file"'\n\s*}!!igs' "$lxde_panel_file"
done

# Delete taskbar
if [ -f "$lxde_panel_file" ]
then
  rm "$lxde_panel_file"
fi

echo "--- Installing chromium"
apt-get install --yes chromium-browser

pushd /home/pi/.config
	mkdir chromium -p
	chown -hR pi:pi chromium
popd

echo "--- Disabling Bluetooth service"
systemctl disable bluetooth
systemctl disable hciuart