#!/usr/bin/env bash
#set -x
echo "" > /dev/null

source /common.sh
install_chroot_fail_on_error_trap

mkdir /home/pi/.config -p
chown -hR pi:pi /home/pi/.config

apt-get update

apt-get install --yes raspberrypi-ui-mods lightdm pcmanfm xinit lxterminal xinput
#apt-get install --yes xorg xinit xinput lightdm pcmanfm plymouth

echo "--- Removing unnecessary stuff"
apt-get purge --yes gnome-keyring pulseaudio

echo "--- Setting up to boot to desktop"
systemctl set-default graphical.target

echo "--- Removing uninstalled applications from desktop"
rm /usr/share/raspi-ui-overrides/applications/*

echo "--- Stop lxpanel from starting"
sed -i "s|^\@lxpanel\(.*\)||" /etc/xdg/lxsession/LXDE-pi/autostart
sed -i "s|^\@point-rpi\(.*\)||" /etc/xdg/lxsession/LXDE-pi/autostart

echo "--- Installing chromium"
apt-get install --yes chromium-browser

pushd /home/pi/.config
	mkdir chromium -p
	chown -hR pi:pi chromium
popd

echo "--- Disabling Bluetooth service"
systemctl disable bluetooth
systemctl disable hciuart