#!/bin/sh
### BEGIN INIT INFO
# Provides:          factoryreset
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Resets the Leapfrog software to factory defaults by flashing the root partition with the recovery partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

backuppart=/dev/mmcblk0p5
mountdir="/backup"
rootbackup="root.img.gz"
homebackup="home.img.gz"

recoverypart=/dev/mmcblk0p6
rootpart=/dev/mmcblk0p2
homepart=/dev/mmcblk0p7

skipfile=/boot/nofactoryreset

do_start () {

  if [ -f "$skipfile" ]; then
      echo "$skipfile found. Skipping factoryreset." >> /var/log/factoryreset
      exit 1;
  fi

	# Show image overlay
  fbi -noverbose -once -T 1 /usr/share/factoryreset/lpfrg-factoryreset-portrait.png&

  mkdir $mountdir -p
  mount $backuppart $mountdir

  # Start copying old 
  echo "Restoring root partition" >> /var/log/factoryreset
  gunzip -c "$mountdir/$rootbackup" | dd of="$rootpart" >> /var/log/factoryreset

  echo "Restoring home partition" >> /var/log/factoryreset
  gunzip -c "$mountdir/$homebackup" | dd of="$homepart" >> /var/log/factoryreset

	# Reset boot partition and reboot	
	sed -i "s@root=$recoverypart@root=$rootpart@" /boot/cmdline.txt

	reboot
}

case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: change_password [start|stop]" >&2
        exit 3
        ;;
esac
