#!/bin/sh
### BEGIN INIT INFO
# Provides:          factoryreset
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Resets the Leapfrog software to factory defaults by flashing the root partition with the recovery partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

logfile="/var/log/factoryreset"
resettypefile="/boot/factoryreset.txt"

PIDFILE=/var/run/factoryreset.pid
DAEMON=/usr/bin/factoryreset

MONITORPIDFILE=/var/run/factoryresetmonitor.pid
MONITORDAEMON=/usr/bin/factoryresetmonitor


do_start () {
  resettype=`cat "$resettypefile"`
  if [ "$resettype" = "full" ] || [ "$resettype" = "fast" ]; then
      echo "Resettype $resettype. Starting daemons..." >> $logfile

      start-stop-daemon --start --background --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON
      start-stop-daemon --start --background --quiet --pidfile $MONITORPIDFILE --make-pidfile --startas /bin/bash -- -c "exec $MONITORDAEMON"

      exit 0
  else
      echo "Resettype none or not recognized. Skipping factoryreset." >> $logfile
      exit 0
  fi
}

do_stop () {

  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $MONITORPIDFILE
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
  
  exit 0

}


case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        do_stop
        ;;
  *)
        echo "Usage: change_password [start|stop]" >&2
        exit 3
        ;;
esac
