#!/bin/sh
### BEGIN INIT INFO
# Provides:          factoryreset
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Resets the Leapfrog software to factory defaults by flashing the root partition with the recovery partition
# Description:
### END INIT INFO

. /lib/lsb/init-functions

logfile="/var/log/factoryreset"

PIDFILE=/var/run/factoryreset.pid
DAEMON=/usr/bin/factoryreset

MONITORPIDFILE=/var/run/factoryresetmonitor.pid
MONITORDAEMON=/usr/bin/factoryresetmonitor


do_start () {

  if [ -f "$skipfile" ]; then
      echo "$skipfile found. Skipping factoryreset." >> $logfile
      exit 0
  fi

  start-stop-daemon --start --background --quiet --pidfile $PIDFILE --make-pidfile --exec $DAEMON
  start-stop-daemon --start --background --quiet --pidfile $MONITORPIDFILE --make-pidfile --exec $MONITORDAEMON
  
  exit 0
	
}

do_stop () {

  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $MONITORPIDFILE
  start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE
  
  exit 0

}


case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        do_stop
        ;;
  *)
        echo "Usage: change_password [start|stop]" >&2
        exit 3
        ;;
esac
