#!/bin/sh
### BEGIN INIT INFO
# Provides:          prepare_rootreadonly
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Preparing to make root read only
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
  . /boot/octopi.txt

  if [ "$perform_resize" != "no" && $(ls /etc/rc3.d/ | grep "prepare_resize" -q) ]
  then
    log_success_msg "Waiting for root/home resize to complete"
    exit 0
  fi

  if [ "$root_readonly" = "yes" ]
  then
    if [ $(cat /boot/cmdline.txt | grep "boot=overlay" -q) ]; then
      log_success_msg "Root already readonly, doing nothing..."
      exit 0
    else
      /usr/bin/root-readonly >> /var/log/prepare_rootreadonly
      #/usr/sbin/update-rc.d prepare_rootreadonly remove >> /var/log/prepare_rootreadonly

      log_success_msg "Root made readonly, rebooting to apply..."
      /sbin/reboot

      exit 0
    fi
  else
    if [ $(cat /boot/cmdline.txt | grep "boot=overlay" -q) ]; then
      sed -i "s/boot=overlay//" /boot/cmdline.txt
      log_success_msg "Root made writable"
      exit 0
    else
      log_failure_msg "Root readonly disabled"
      exit 0
    fi
  fi



}

echo "First parameter is $1" >> /var/log/prepare_rootreadonly
case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: prepare_resize [start|stop]" >&2
        exit 3
        ;;
esac