#!/bin/sh
### BEGIN INIT INFO
# Provides:          prepare_rootreadonly
# Required-Start:    $local_fs
# Required-Stop:
# Default-Start:     3
# Default-Stop:
# Short-Description: Preparing to make root read only
# Description:
### END INIT INFO

. /lib/lsb/init-functions

do_start () {
  . /boot/octopi.txt

  systemctl is-enabled "prepare_resize"
  prepare_resize_exists=$?

  #ls /etc/init.d/ | grep -q "resize2fs_once" || ls /etc/init.d/ | grep -q "homeresize2fs_once"
  #resize_once_exists=$?

  cat /boot/cmdline.txt | grep -q "boot=overlay"
  is_already_readonly=$?
#  if [ "$perform_resize" != "no" ] && { [ "$prepare_resize_exists" = 0 ] || [ "$resize_once_exists" = 0 ]; }
  if [ "$perform_resize" != "no" ] && [ "$prepare_resize_exists" = 0 ]
  then
    echo "Waiting for root/home resize to complete" >> /var/log/prepare_rootreadonly
    exit 0
  fi

  if [ "$root_readonly" = "yes" ]
  then
    if [ "$is_already_readonly" = 0 ]; then
      echo "Root already readonly, doing nothing..." >> /var/log/prepare_rootreadonly
      exit 0
    else
      echo "Going to make root readonly" >> /var/log/prepare_rootreadonly
      /usr/bin/root-readonly >> /var/log/prepare_rootreadonly
      #/usr/sbin/update-rc.d prepare_rootreadonly remove >> /var/log/prepare_rootreadonly

      echo "Root made readonly, rebooting to apply..." >> /var/log/prepare_rootreadonly
      /sbin/reboot

      exit 0
    fi
  else

    if [ "$is_already_readonly" = 0 ]; then
      sed -i "s/boot=overlay//" /boot/cmdline.txt
      echo "Root made writable" >> /var/log/prepare_rootreadonly
      /sbin/reboot
      exit 0
    else
      echo "Root readonly disabled" >> /var/log/prepare_rootreadonly
      exit 0
    fi
  fi



}

echo "First parameter is $1" >> /var/log/prepare_rootreadonly
case "$1" in
  start|"")
        do_start
        ;;
  restart|reload|force-reload)
        echo "Error: argument '$1' not supported" >&2
        exit 3
        ;;
  stop)
        # No-op
        ;;
  *)
        echo "Usage: prepare_resize [start|stop]" >&2
        exit 3
        ;;
esac