#!/usr/bin/env bash
#set -x
set -e
# Helper script that runs in a chroot to create the recovery environment
# Author: Erik Heidstra <ErikHeidstra@live.nl>

export LC_ALL=C

source /common.sh
install_cleanup_trap

apt-get update

echo "--- Copying additional LPFRG files"
unpack /filesystem/root_recovery /

echo "--- Installing FBI"
apt-get install --yes fbi

echo "--- Installing ImageMagick"
apt-get install --yes imagemagick

echo "--- Installing factoryreset"
chmod +x /etc/init.d/factoryreset
chmod +x /usr/bin/factoryreset
chmod +x /usr/bin/factoryresetmonitor
update-rc.d factoryreset defaults

echo "--- Update pi password"
if [ -n $OCTOPI_PI_PASSWORD ]
then
	echo "pi:$OCTOPI_PI_PASSWORD" | chpasswd
fi

echo "--- Setting up to boot to desktop"
systemctl set-default graphical.target

# DHCP optimization (for boot speedup)
grep -q "noarp" /etc/dhcpcd.conf || echo "noarp" >> /etc/dhcpcd.conf
rm /etc/systemd/system/dhcpcd.service.d/wait.conf

#cleanup
apt-get clean
apt-get autoremove -y