#!/usr/bin/env bash
set -x
set -e
# Helper script that runs in a DietPi chroot to create the recovery environment
# Written by Erik Heidstra <ErikHeidstra@live.nl>
# GPL V3

export LC_ALL=C

source /common.sh
install_cleanup_trap

# Keeping it offline for now

#apt-get update

echo "--- Copying additional LPFRG files"
unpack /filesystem/root_recovery /

#echo "--- Installing OpenSSH"
#apt-get install --yes openssh-server

echo "--- Installing factoryreset"
chmod +x /etc/init.d/factoryreset
update-rc.d factoryreset defaults

#cleanup
#apt-get clean
#apt-get autoremove -y